on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install libcurl and libxml2
        runs: sudo apt-get install libcurl-dev libxml2-dev

      - name: Build
        runs: mkdir build && cd build && cmake .. && make
